# Use an official Python runtime as the base image
FROM --platform=linux/amd64 python:3.9 as base

# Add alias to user profile
RUN echo "alias ll='ls -la'" >> /root/.bashrc

# Set the working directory in the container
WORKDIR /server

# Note this will ignore items in .dockerignore
# Copy the requirements.txt file to the container
COPY server/. .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

CMD ["./python-server-up.sh"]
